experiment:
  name: "Emotion_Memory_KV_Retrieval_Experiment"
  
  # Model configuration
  model_path: "/data/home/jjl7137/huggingface_models/Qwen/Qwen2.5-0.5B-Instruct"
  
  # Emotions to test
  emotions:
    - "anger"
    - "happiness"
    - "sadness"
  
  # Emotion intensity levels
  intensities:
    - 1.0
    - 1.5
  
  # Benchmark configuration
  benchmark:
    name: "infinitebench"
    data_path: "/data/home/jjl7137/memory_benchmarks/InfiniteBench/data/kv_retrieval.jsonl"
    task_type: "kv_retrieval"
    evaluation_method: "get_score_one_kv_retrieval"
    sample_limit: 50
    metadata:
      description: "Key-value retrieval from long context"
      context_length: "100k+"
      task_difficulty: "medium"
  
  # Generation parameters
  generation_config:
    temperature: 0.0
    max_new_tokens: 100
    do_sample: false
    top_p: 1.0
  
  # Experimental parameters
  batch_size: 2
  
  # Output configuration
  output:
    base_dir: "results/emotion_memory_kv"
    save_plots: true
    plot_format: "png"