experiment:
  name: "Comprehensive_Emotion_Memory_Experiment"
  
  # Model configuration
  model_path: "/data/home/jjl7137/huggingface_models/Qwen/Qwen2.5-0.5B-Instruct"
  
  # Full emotion set
  emotions:
    - "anger"
    - "happiness"
    - "sadness"
    - "disgust"
    - "fear"
    - "surprise"
  
  # Multiple intensity levels for detailed analysis
  intensities:
    - 0.3
    - 0.7
    - 1.0
    - 1.3
    - 1.7
  
  # Benchmark configuration
  benchmark:
    name: "infinitebench"
    data_path: "/data/home/jjl7137/memory_benchmarks/InfiniteBench/data/longbook_qa_eng.jsonl"
    task_type: "longbook_qa_eng"
    evaluation_method: "get_score_one_longbook_qa_eng"
    sample_limit: 200  # Larger sample for statistical significance
    metadata:
      description: "Long book reading comprehension"
      context_length: "100k+"
      task_difficulty: "hard"
      source: "InfiniteBench dataset"
      evaluation_metric: "accuracy"
  
  # Advanced generation parameters
  generation_config:
    temperature: 0.2
    max_new_tokens: 200
    do_sample: true
    top_p: 0.95
    top_k: 50
    repetition_penalty: 1.1
  
  # Experimental parameters
  batch_size: 8  # Larger batch for efficiency
  
  # Output configuration
  output:
    base_dir: "results/comprehensive_emotion_memory"
    save_plots: true
    plot_format: "both"  # Custom extension - save as png and pdf
    
  # Optional: Advanced experimental settings
  advanced:
    run_sanity_check: true
    sanity_check_samples: 5
    enable_detailed_logging: true
    save_intermediate_results: true