# Emotion Check Validation Configuration
# Simple test to verify emotion manipulation is working in memory experiments

experiment_name: "emotion_check_validation"
description: "Basic emotion validation test using direct questions and one-word responses"
version: "1.0.0"

# Single model for quick testing - use a small model for speed
models:
  - "Qwen/Qwen2.5-1.5B-Instruct"

# Our emotion check benchmark
benchmarks:
  - name: "emotion_check"
    task_type: "basic_validation"
    base_data_dir: "data/emotion_scales"  # Updated data directory location
    llm_eval_config:
      model: "gpt-4.1-mini"
      temperature: 0.1
      evaluation_prompt: |
        You are evaluating whether a response indicates a specific emotion. 
        
        Question: {question}
        Response: {response}
        
        First, check if the response fits clearly into one of these 6 basic emotion categories:
        - anger (angry, mad, furious, irritated, frustrated)
        - happiness (happy, joyful, pleased, content, excited)
        - sadness (sad, depressed, melancholy, down, sorrowful)
        - fear (afraid, scared, anxious, worried, nervous)
        - disgust (disgusted, revolted, repulsed, sickened)
        - surprise (surprised, amazed, astonished, shocked, startled)
        
        If the response doesn't fit clearly into any basic emotion, check these:
        - neutral (calm, peaceful, fine, okay, no strong emotion expressed)
        - other (mixed emotions, complex emotional states, confusion, or emotions not in the basic 6)
        
        IMPORTANT: Use "other" for:
        - Complex emotions (overwhelmed, stressed, confused, grateful, proud, guilty)
        - Uncertain emotional states ("not sure how I feel")
        - Any emotion that doesn't clearly fit the basic 6 categories
        
        Return your answer as JSON in this exact format:
        {{"rationale": "reasoning", "emotion": "category_name", "confidence": 0.95}}
        
        Where category_name is one of: anger, happiness, sadness, fear, disgust, surprise, neutral, other
        And confidence is a number between 0.0 and 1.0.

# Test all 6 core emotions plus neutral baseline
emotions: ["anger", "happiness", "sadness", "fear", "disgust", "surprise"]
intensities: [1.5]  # Use full intensity for clear effects

# vLLM loading configuration for lightweight model
loading_config:
  model_path: null  # Will be set by runner for each model
  gpu_memory_utilization: 0.90
  tensor_parallel_size: null  # Auto-detect
  max_model_len: 4096  # Short context sufficient for emotion questions
  enforce_eager: true
  quantization: null
  trust_remote_code: true
  dtype: "float16"
  seed: 42
  disable_custom_all_reduce: false
  additional_vllm_kwargs: {}

# RepE configuration
repe_eng_config:
  direction_method: "pca"

# Generation parameters for natural responses
generation_config:
  temperature: 0.7  # Allow more varied responses
  max_new_tokens: 100  # Allow fuller emotional descriptions
  do_sample: true
  top_p: 0.9
  repetition_penalty: 1.0
  top_k: -1
  min_p: 0.0
  presence_penalty: 0.0
  frequency_penalty: 0.0
  enable_thinking: false

# Execution settings - small batches for quick testing
batch_size: 10
max_evaluation_workers: 2
pipeline_queue_size: 2

# Output configuration
output_dir: "results/emotion_check_validation"

# Run sanity check mode for quick validation
run_sanity_check: true
