experiment:
  name: "escalation_game_previous_actions_2"
  game:
    name: "Escalation_Game" 
    previous_actions_length: 2
  data:
    generate: false  # Set to false to skip data generation
    num_scenarios: 36
    batch_size: 4

  llm:
    llm_config: "OAI_CONFIG"  # Name of the config from api_configs.py
    # Additional parameters to override or extend the base config
    generation_config:
      temperature: 0.7
      model: "gpt-4o"

  # Template for system message with placeholders
  system_message_template: "You are Alice, an average American. You feel {intensity} {emotion}, because {stimulus}."

  intensity:
    - "100%"

  emotions:
    - "anger"
    - "happiness"
    - "sadness"
    - "disgust"
    - "fear"
    - "surprise"
    
  repeat: 5

  output:
    base_dir: "results"
    save_plots: true
    plot_format: "png" 