experiment:
  name: "Gemma3_MM_Series_Sequential_Games"
  
  # List of games to run experiments with
  # Available games: Escalation_Game, Trust_Game_Trustor, Trust_Game_Trustee, 
  #                  Ultimatum_Game_Proposer, Ultimatum_Game_Responder
  games:
    - "Escalation_Game"
    - "Trust_Game_Trustor"
    - "Trust_Game_Trustee"
    - "Ultimatum_Game_Proposer"
    - "Ultimatum_Game_Responder"
  
  # Individual game configurations with specific attributes
  # Each game may require different parameters based on its game mechanics
  games_config:
    Escalation_Game:
      previous_actions_length: 0  # Can be 0, 1, or 2 depending on escalation rounds
      
    Trust_Game_Trustor:
      previous_actions_length: 0  # Trustor moves first, no previous actions
      
    Trust_Game_Trustee:
      previous_actions_length: 1  # Trustee responds to trustor's action
      previous_trust_level: 0     # 0=trust_low, 1=trust_high (trustor's previous choice)
      
    Ultimatum_Game_Proposer:
      previous_actions_length: 0  # Proposer moves first, no previous actions
      
    Ultimatum_Game_Responder:
      previous_actions_length: 1  # Responder reacts to proposer's offer
      previous_offer_level: 0     # 0=offer_low, 1=offer_medium, 2=offer_high (proposer's previous choice)
  
  # List of Gemma 3 models to test (multimodal variants only)
  # Note: Only 4B, 12B, and 27B support multimodal; 270M and 1B are text-only
  models: 
    - "/data/home/jjl7137/huggingface_models/google/gemma-3-4b-it"
    - "/data/home/jjl7137/huggingface_models/google/gemma-3-12b-it"
    - "/data/home/jjl7137/huggingface_models/google/gemma-3-27b-it"
    # Add more models as needed
  
  data:
    generate: false # generate game data if true
    num_scenarios: 36
    batch_size: 4
  
  llm:
    model_name: 'google/gemma-3-4b-it'  # Default model if needed (fallback)
    # Additional parameters to override or extend the base config
    generation_config:
      temperature: 0.7
      do_sample: true
      top_p: 0.95
      max_new_tokens: 440

  batch_size: 500

  # Template for system message with placeholders
  system_message_template: "Remember you are Alice. What is your option? Choose one option shown above."
  
  repeat: 1

  # Emotional states to test across all games
  emotions:
    - "anger"
    - "happiness"
    - "sadness"
    - "disgust"
    - "fear"
    - "surprise"

  # Emotional intensity levels
  intensity:
    - 1.5

  run_sanity_check: true

  output:
    base_dir: "results/Gemma3_MM_Series_Sequential_Games"
    save_plots: true
    plot_format: "png"

# Multimodal configuration section for emotion-based visual stimuli
repe_config:
  # Essential for multimodal processing
  multimodal_intent: true
  data_dir: "data/image"  # Points to directory with emotion JSON files
  emotions: ["happiness", "sadness", "anger", "fear", "disgust"]
  rebuild: false