# Option Probability Experiment Configuration
# This config defines the experimental conditions and parameters

experiment:
  name: "emotion_context_option_probability"
  description: "2x2 factorial experiment measuring emotion and context effects on choice probabilities"
  
  # Experimental factors
  emotions:
    - "neutral"
    - "anger"
  
  emotion_intensities:
    - 0.0  # neutral baseline
    - 1.5  # high intensity (optional)
  
  # Context manipulation settings
  context_conditions:
    - "with_description"
    - "without_description"
  
  # Sampling and batch settings
  sample_num: 100  # Number of scenarios per condition (null for all)
  batch_size: 100    # Batch size for processing
  
  # Output configuration
  output:
    base_dir: "results/Context_Effect"
    save_raw_results: true
    save_statistical_analysis: true
    save_summary_report: true
    
  # Statistical analysis settings
  statistical_analysis:
    enable_interaction_tests: true
    enable_pairwise_comparisons: true
    significance_level: 0.05
    multiple_comparison_correction: "bonferroni"  # or "fdr_bh"
    
# Representation Engineering Configuration
repe_config:
  model_name_or_path: "/data/home/jjl7137/huggingface_models/Qwen/Qwen2.5-0.5B-Instruct"
  
  # vLLM settings
  tensor_parallel_size: 4
  gpu_memory_utilization: 0.85
  max_num_seqs: 16
  enforce_eager: true
  trust_remote_code: true
  
  # Representation control settings (for future use)
  control_method: "reading_vec"
  block_name: "decoder_block"
  coeffs: [0.0, 1.5]
  
  # Layer selection for control (if needed)
  control_layers: "middle_third"  # options: "all", "middle_third", "last_third", [1,2,3]
  
# Game Configuration
game_config:
  game_name: "prisoners_dilemma"
  data_path: "data_creation/scenario_creation/langgraph_creation/Prisoners_Dilemma_all_data_samples_4.1_distinct_choices.json"
  
  # Decision format
  decision_class: "binary_choice"  # or "multiple_choice", "text_generation"
  
  # Prompt settings
  include_payoff_matrix: true
  include_context_description: true  # Can be overridden by experiment conditions

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file_prefix: "option_probability_experiment"
  include_timestamps: true
  include_model_outputs: false  # Set to true for debugging 