experiment:
  name: "priDeli_neural_anger_test"
  game:
    name: "Prisoners_Dilemma"
    
  data:
    generate: false  # Use existing data - no need to generate new scenarios
    num_scenarios: 36
    batch_size: 4
  
  max_test_scenarios: 300  # Randomly sample 300 scenarios for testing
  
  llm:
    llm_config: "LOCAL_SERVER_NEUTRAL_CONFIG"  # Will be switched to LOCAL_SERVER_ANGER_CONFIG for anger test
    generation_config:
      model: "Qwen2.5-0.5B-Instruct"
      temperature: 0.7
      seed: 43

  # Neutral system message - no prompt-level emotion manipulation
  # All emotion control happens at neural level via server
  system_message_template: "You are Alice, an average American."

  repeat: 2  # Reasonable repeats for 300 scenarios (600 total decisions)

  # Simplified for neural testing - server handles emotion activation
  intensity:
    - "neutral"

  emotions:
    - "happiness"  # Emotion controlled by server, not prompt

  output:
    base_dir: "results/neural_test"
    save_plots: true
    plot_format: "png"