experiment:
  name: "priDeli_gpt4o"
  game:
    name: "Prisoners_Dilemma"  # or "Prisoners_Dilemma"
    
  data:
    generate: false  # Set to false to skip data generation
    num_scenarios: 36
    batch_size: 4
  
  llm:
    llm_config: "OAI_CONFIG"  # Name of the config from api_configs.py
    # Additional parameters to override or extend the base config
    generation_config:
      model: "gpt-4o"
      temperature: 0.7
      seed: 43

  # Template for system message with placeholders
  # system_message_template: "You are Alice, an average American. You feel {intensity} {emotion}, because {stimulus}."
  system_message_template: "You are Alice. You just experienced the following: {stimulus}. Remember the above memory and {intensity} feeling firmly in all unseen scenarios."

  repeat: 2

  intensity:
    - "strong"
    # - "medium"
    # - "weak"


  emotions:
    - "anger"
    - "disgust"
    - "fear"
    - "happiness"
    - "sadness"
    - "surprise"

  output:
    base_dir: "results/promptEng"
    save_plots: true
    plot_format: "png" 