experiment:
  name: "emotion_game_theory"
  game:
    name: "Prisoners_Dilemma"  # or "Prisoners_Dilemma"
    
  data:
    generate: false  # Set to false to skip data generation
    num_scenarios: 36
    batch_size: 4
  
  llm:
    llm_config: "OAI_CONFIG"  # Name of the config from api_configs.py
    # Additional parameters to override or extend the base config
    generation_config:
      model: "gpt-4o"
      temperature: 0.7
      seed: 43

  # Template for system message with placeholders
  system_message_template: "You are Alice, an average American. You feel 90% {emotion}, because {stimulus}."

  repeat: 1

  emotions:
    - "anger"
    - "happiness"
    
  output:
    base_dir: "results"
    save_plots: true
    plot_format: "png" 