experiment:
  name: "Qwen2.5_MM_Series_Prisoners_Dilemma"
  
  # List of games to run experiments with
  games:
    - "Prisoners_Dilemma"
  
  # List of models to run experiments with
  models: 
    - "/data/home/jjl7137/huggingface_models/Qwen/Qwen2.5-VL-3B-Instruct"
    - "/data/home/jjl7137/huggingface_models/Qwen/Qwen2.5-VL-7B-Instruct"
    # Add more models as needed
  
  game:
    name: "Prisoners_Dilemma"  # Default game if needed
    # Additional game parameters
    previous_actions_length: 0
    
  data:
    generate: false # generate game data if true
    num_scenarios: 36
    batch_size: 4
  
  llm:
    model_name: 'meta-llama/Llama-3.1-8B-Instruct'  # Default model if needed
    # Additional parameters to override or extend the base config
    generation_config:
      temperature: 0.7
      do_sample: true
      top_p: 0.95
      max_new_tokens: 440

  # Template for system message with placeholders
  system_message_template: "Remember you are Alice. What is your option? Choose one option shown above."
  
  repeat: 1

  emotions:
    - "anger"
    - "happiness"
    - "sadness"
    - "disgust"
    - "fear"
      #  - "surprise"

  intensity:
    - 1.5

  run_sanity_check: false

  output:
    base_dir: "results/Qwen2.5_MM_Series_Prisoners_Dilemma"
    save_plots: true
    plot_format: "png"

# New repe_config section for multimodal configuration
repe_config:
  # Essential for multimodal processing
  multimodal_intent: true
  data_dir: "data/image"  # Points to directory with emotion JSON files
  emotions: ["happiness", "sadness", "anger", "fear", "disgust"]
  rebuild: false
