experiment:
  name: "Qwen3_Series_none_thinking"
  
  
  # List of models to run experiments with
  models: 
    - "/data/home/jjl7137/huggingface_models/Qwen/Qwen3-0.6B"
    - "/data/home/jjl7137/huggingface_models/Qwen/Qwen3-1.7B"
    - "/data/home/jjl7137/huggingface_models/Qwen/Qwen3-4B-AWQ"
    - "/data/home/jjl7137/huggingface_models/Qwen/Qwen3-8B-AWQ"
    - "/data/home/jjl7137/huggingface_models/Qwen/Qwen3-14B-AWQ"
  
  # List of games to run experiments with
  games:
    - "Prisoners_Dilemma"
    - "Escalation_Game"
    - "Trust_Game_Trustor"
      #- "Trust_Game_Trustee"
    - "Ultimatum_Game_Proposer"
      #- "Ultimatum_Game_Responder"

  games_config:
    Escalation_Game:
      previous_actions_length: 0  # Can be 0, 1, or 2 depending on escalation rounds
      
    Trust_Game_Trustor:
      previous_actions_length: 0  # Trustor moves first, no previous actions
      
    Trust_Game_Trustee:
      previous_actions_length: 1  # Trustee responds to trustor's action
      previous_trust_level: 0     # 0=trust_low, 1=trust_high (trustor's previous choice)
      
    Ultimatum_Game_Proposer:
      previous_actions_length: 0  # Proposer moves first, no previous actions
      
    Ultimatum_Game_Responder:
      previous_actions_length: 1  # Responder reacts to proposer's offer
      previous_offer_level: 0     # 0=offer_low, 1=offer_medium, 2=offer_high (proposer's previous choice)  


  data:
    generate: false
    num_scenarios: 36
    batch_size: 4
  
  llm:
    # Qwen3 specific parameters
    generation_config:
      temperature: 0.7
      do_sample: true
      top_p: 0.95
      max_new_tokens: 28000
      # Thinking mode enabled
      enable_thinking: false

  system_message_template: "Remember you are Alice. What is your option? Choose one option shown above."
  
  repeat: 1

  emotions:
    - "anger"
    - "happiness"
    - "sadness"
    - "disgust" 
    - "fear"
    - "surprise"

  intensity:
    - 1.5


  run_sanity_check: false

  output:
    base_dir: "results/Qwen3_Series_none_thinking"
    save_plots: true
    plot_format: "png"
