experiment:
  name: "emotion_game_theory"
  game:
    name: "Stag_Hunt" 
    
  data:
    generate: false  # Set to false to skip data generation
    num_scenarios: 36
    batch_size: 4
  
  llm:
    llm_config: "OAI_CONFIG"  # Name of the config from api_configs.py
    # Additional parameters to override or extend the base config
    generation_config:
      temperature: 0.7
      seed: 43
      model: "gpt-4o"

  emotions:
    - "anger"
    - "happiness"
    - "sadness"
    - "disgust"
    - "fear"
    - "surprise"
    
  output:
    base_dir: "results"
    save_plots: true
    plot_format: "png" 