experiment:
  name: "test_neural_happiness"
  game:
    name: "Prisoners_Dilemma"
    
  data:
    generate: false  # Use existing data - no need to generate new scenarios
    num_scenarios: 36
    batch_size: 4
  
  max_test_scenarios: 5  # Test with just 5 scenarios
  
  llm:
    llm_config: "LOCAL_SERVER_NEUTRAL_CONFIG"  # Happiness server
    generation_config:
      model: "Qwen2.5-0.5B-Instruct"
      temperature: 0.7
      seed: 43

  # Neutral system message - no prompt-level emotion manipulation
  # All emotion control happens at neural level via server
  system_message_template: "You are Alice, an average American."

  repeat: 2  # Just 2 repeats for testing

  # Simplified for neural testing - server handles emotion activation
  intensity:
    - "neutral"

  emotions:
    - "happiness"  # Emotion controlled by server, not prompt

  output:
    base_dir: "results/neural_test"
    save_plots: true
    plot_format: "png"