experiment:
  name: test_emotion_game
  game:
    name: prisoners_dilemma  # Using prisoners dilemma as test game
  
  llm:
    model_name: /data/home/jjl7137/huggingface_models/RWKV/rwkv-4-world-7b
    generation_config:
      max_new_tokens: 100
      do_sample: true
      top_p: 0.9
      temperature: 0.7
  output:
    base_dir: test_output
  system_message_template: |
    You are playing a game with emotion {emotion}. 
    Please make a decision based on the scenario.
  repeat: 2
  intensity: [0.5, 1.0]  # Test with two intensity levels

model:
  control_method: activation
  control_layer_id: [-1, -2]  # Test with last two layers
  block_name: mlp
  emotions: 
    - happy
    - sad
  coeffs: [0.5, 1.0]

game:
  decision_class:
    decision: str
    rationale: str
    option_id: int
  options:
    - Cooperate
    - Defect