models:
  - /data/home/jjl7137/huggingface_models/Qwen/Qwen2.5-0.5B-Instruct

benchmarks:
  - name: trustllm_privacy
    task_type: privacy_awareness_confAide
    data_path: data/TrustLLM/tmp/privacy_confide_sample.json
    sample_limit: 2
    llm_eval_config:
      model: gpt-4o-mini
      temperature: 0.0

  - name: trustllm_privacy
    task_type: privacy_awareness_query
    data_path: data/TrustLLM/tmp/privacy_query_sample.json
    sample_limit: 2
    llm_eval_config:
      model: gpt-4o-mini
      temperature: 0.0

  - name: trustllm_privacy
    task_type: privacy_leakage
    data_path: data/TrustLLM/tmp/privacy_leakage_sample.json
    sample_limit: 2
    llm_eval_config:
      model: gpt-4o-mini
      temperature: 0.0

emotions: [anger]
intensities: [1.0]

output_dir: results/TrustLLM_privacy
batch_size: 1

sanity_check: true
sanity_check_limit: 2

generation_config:
  temperature: 0.0
  max_new_tokens: 64
  do_sample: false

loading_config:
  gpu_memory_utilization: 0.90
  tensor_parallel_size: 1
  max_model_len: 4096
  enforce_eager: true
  trust_remote_code: true
  dtype: float16
  seed: 42
  disable_custom_all_reduce: false
  additional_vllm_kwargs: {}
