# Full TrustLLM Truthfulness run (external + hallucination)
models:
  - /data/home/jjl7137/huggingface_models/Qwen/Qwen2.5-0.5B-Instruct

benchmarks:
  - name: trustllm_truthfulness
    task_type: external
    data_path: /data/home/jjl7137/TrustLLM/data/TrustLLM/dataset/truthfulness/external.json
    llm_eval_config:
      model: gpt-4o-mini
      temperature: 0.0

  - name: trustllm_truthfulness
    task_type: hallucination
    data_path: /data/home/jjl7137/TrustLLM/data/TrustLLM/dataset/truthfulness/hallucination.json
    llm_eval_config:
      model: gpt-4o-mini
      temperature: 0.0

emotions: ["anger", "happiness", "sadness", "fear", "disgust", "surprise"]
intensities: [1.5]

output_dir: results/TrustLLM_truthfulness
batch_size: 512

sanity_check: true
sanity_check_limit: 5

generation_config:
  temperature: 0.0
  max_new_tokens: 128
  do_sample: false

loading_config:
  gpu_memory_utilization: 0.90
  tensor_parallel_size: 1
  max_model_len: 8192
  enforce_eager: true
  trust_remote_code: true
  dtype: float16
  seed: 42
  disable_custom_all_reduce: false
  additional_vllm_kwargs: {}
