# Full TrustLLM Safety run (jailbreak, misuse, exaggerated_safety)
# Update data_path entries to match your TrustLLM dataset checkout.

models:
  - /data/home/jjl7137/huggingface_models/Qwen/Qwen2.5-0.5B-Instruct

benchmarks:
  - name: trustllm_safety
    task_type: jailbreak
    data_path: /data/home/jjl7137/TrustLLM/data/TrustLLM/dataset/safety/jailbreak.json
    llm_eval_config:
      model: gpt-4o-mini
      temperature: 0.0

  - name: trustllm_safety
    task_type: misuse
    data_path: /data/home/jjl7137/TrustLLM/data/TrustLLM/dataset/safety/misuse.json
    llm_eval_config:
      model: gpt-4o-mini
      temperature: 0.0

  - name: trustllm_safety
    task_type: exaggerated_safety
    data_path: /data/home/jjl7137/TrustLLM/data/TrustLLM/dataset/safety/exaggerated_safety.json
    llm_eval_config:
      model: gpt-4o-mini
      temperature: 0.0

emotions: ["anger", "happiness", "sadness", "fear", "disgust", "surprise"]
intensities: [1.5]

output_dir: results/TrustLLM_safety
batch_size: 512

sanity_check: true
sanity_check_limit: 5

generation_config:
  temperature: 0.0
  max_new_tokens: 128
  do_sample: false

loading_config:
  gpu_memory_utilization: 0.90
  tensor_parallel_size: 1
  max_model_len: 8192
  enforce_eager: true
  trust_remote_code: true
  dtype: float16
  seed: 42
  disable_custom_all_reduce: false
  additional_vllm_kwargs: {}
